### ISSUE TITLE
Musica

### ISSUE THREAD

**Issue by gtotaro** [pdepjuevesTT/presentacion-AgusDS99#1]
Hola, algún disco a destacar de Pink Floyd?

**Comment by desousamagustin** [comment]
Hola! Uno de mis álbumes favoritos y más conocidos es "The dark side of the moon". Te recomiendo no solo escuchar la música sino también buscar la letra. La mayoría de las canciones tocan temas muy filosóficos.

**Comment by gtotaro** [comment]
Hola, es un album que tiene todo para escuchar y escuchar.
